service: serverless-api-minimum
frameworkVersion: '3'

provider:
  name: aws
  profile: default
  stage: dev
  region: ap-northeast-1
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  api:
    handler: dist/index.handler
    events:
      - http:
          path: '/'
          method: any
      - http:
          path: '{proxy+}'
          method: any
