service: hello-serverless-api
frameworkVersion: '3'

provider:
  name: aws
  profile: default
  stage: dev
  region: ap-northeast-1
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'
